services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: web
    container_name: cakephp_web
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USERNAME: user
      DB_PASSWORD: pass
      DB_DATABASE: brazilian_outlets_db
      DEBUG: true

  db:
    image: mysql:5.7
    container_name: cakephp_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: brazilian_outlets_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db

  cron:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: cron
    container_name: cakephp_cron
    volumes:
      - ./src:/var/www/html
    depends_on:
      - web
    environment:
      DB_HOST: db
      DB_USERNAME: user
      DB_PASSWORD: pass
      DB_DATABASE: brazilian_outlets_db
      DEBUG: false
      EMAIL_CLASS_NAME: Smtp
      EMAIL_HOST: mailhog
      EMAIL_PORT: 1025
      EMAIL_USERNAME: null
      EMAIL_PASSWORD: null
      EMAIL_TLS: null

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  db_data: